### ISSUE TITLE
Failed to install cargo-binstall on macOS and Windows

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/install-action#10]
cargo-binstall installation started failing on macOS and Windows.
IIUC, this can be fixed by creating a temporary directory and then unzipping the archive there.

macOS: https://github.com/taiki-e/install-action/runs/7491494413?check_suite_focus=true
```
info: installing cargo-binstall
Archive:  cargo-binstall-x86_64-apple-darwin.zip
replace README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
  inflating: LICENSE.txt             
(EOF or read error, treating as "[N]one" ...)
  inflating: cargo-binstall      
```
Windows: https://github.com/taiki-e/install-action/runs/7491494464?check_suite_focus=true
```
info: installing cargo-binstall
Archive:  cargo-binstall-x86_64-pc-windows-msvc.zip
  inflating: LICENSE.txt             
replace README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
  inflating: cargo-binstall.exe  
```

**Comment by NobodyXu** [comment]
Thanks @taiki-e , I didn't even realize that it was broken.

This failure is because we includes LICENSE.txt and README.md in the release and I forgot to update install-action.
