### ISSUE TITLE
Add support for tree-sitter-cli

### ISSUE THREAD

**Issue by ajeetdsouza** [taiki-e/install-action#108]
Binary releases available at https://github.com/tree-sitter/tree-sitter/releases/

**Comment by NobodyXu** [comment]
I recommend you to [add support of cargo-binstall](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md) to tree-sitter-cli, it would then not only makes it possible for taiki-e/install-actions but also for all users using cargo-binstall.

**Comment by ajeetdsouza** [comment]
Ah, I wasn't aware that install-action falls back to binstall. This works, thanks!
