### ISSUE TITLE
Trim whitespace from tool names

### ISSUE THREAD

**Issue by daemontus** [taiki-e/install-action#115]
If I list multiple tools in the `tool` list, the whitespace is included in tool name and the install fails. For example, `tool: cargo-binstall, cargo-tarpaulin` attempts to install " cargo-tarpaulin" which does not exist and is not a valid name anyway. The names of the tools should be trimmed after parsing :)

**Comment by taiki-e** [comment]
It seems reasonable to me.

**Comment by daemontus** [comment]
Awesome! Thank you.

**Comment by taiki-e** [comment]
Published in 2.8.0.
