### ISSUE TITLE
Possible to only use musl binaries if glibc isn't available?

### ISSUE THREAD

**Issue by sunshowers** [taiki-e/install-action#13]
Hi Taiki --

Thanks for continuing to maintain this action :)

Noticed that f343021ffcdd86f8aeb6037ed83341e1a0d45040 switched nextest to using the musl binaries. Unfortunately, the musl build is currently quite a bit slower than the glibc build due to https://github.com/rust-lang/rust/issues/99740. On the clap repo I observed a 2x slowdown going from glibc to musl. (There might be other perf regressions too esp around threading, haven't checked).

Would it be possible to only install the musl binary if glibc isn't available? I'm not sure how hard that would be.

**Comment by NobodyXu** [comment]
It definitely is possible by checking output of rustc -vV (cargo-binstall already does this).

Refarding the slowdown, it is likely the memory allocator of musl being too slow.
I read somewhere that if the binary is built with musl libc with mimalloc, then it is even faster than glibc with mimalloc.

**Comment by sunshowers** [comment]
In this case the slowdown is definitely due to that Rust bug I linked above. It's quite possible that musl is faster once that is fixed in Rust upstream -- we'll have to wait though.

**Comment by NobodyXu** [comment]
@sunshowers Thanks, I missed that link.

In the meantime, you can try cargo-binstall since [cargo-nextest already has support for it](https://github.com/nextest-rs/nextest/blob/d32a41310f400ed656a5d1fd96de8a819176fc09/cargo-nextest/Cargo.toml#L57)

**Comment by sunshowers** [comment]
Oh I'm the primary maintainer of nextest! It's just that most CI users use this action to install it and I'd like to make sure they're using the fastest version of it.

**Comment by taiki-e** [comment]
The reason for using musl by default is not only for compatibility with musl linux hosts, but also for compatibility with linux which uses the old glibc (For example, the [mdbook linux-gnu binary is built on ubuntu 20.04 and is incompatible with ubuntu 18.04](https://github.com/rust-lang/mdBook/issues/1779)).

That said, as long as the prebuilt binary of nextest is compatible with ubuntu 18.04, I'm fine with doing this.

**Comment by sunshowers** [comment]
Yeah, we build nextest against Ubuntu 18.04 because of that glibc compat issue: https://github.com/nextest-rs/nextest/blob/d32a41310f400ed656a5d1fd96de8a819176fc09/.github/workflows/release.yml#L102-L103

**Comment by sunshowers** [comment]
Thanks so much!

**Comment by taiki-e** [comment]
Fixed in 1.8.0.

**Comment by taiki-e** [comment]
> That said, as long as the prebuilt binary of nextest is compatible with ubuntu 18.04, I'm fine with doing this.

follow-up: I have implemented logic to detect the host glibc version (https://github.com/taiki-e/install-action/commit/069858bff79327dc6f51daccd66080401a7ae8f3), so we can support this regardless of the tool's glibc requirements.  (although the various values are hard-coded in main.sh until [generic logic to handle issues around glibc requirements](https://github.com/taiki-e/install-action/issues/5#issuecomment-1364723044) is implemented)
