### ISSUE TITLE
I would like to add support for the tool `syft`

### ISSUE THREAD

**Issue by FirelightFlagboy** [taiki-e/install-action#131]
The project can be found here https://github.com/anchore/syft.

If you're open to new PRs, could you indicate the general steps to include a new tool ?

I may propose a PR with those steps :)

**Comment by taiki-e** [comment]
I would accept a PR to support this.

See [DEVELOPMENT.md](https://github.com/taiki-e/install-action/blob/main/DEVELOPMENT.md) for how to add support for new tool.
