### ISSUE TITLE
Auto-generate tool list for CI

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/install-action#137]
Currently, we are managing these lists manually, which is not a great situation, because people forget to add tool names, merge conflicts occur between PRs, etc.

https://github.com/taiki-e/install-action/blob/93a5b91855ce53b049b56dc66eecf1cf411e6057/.github/workflows/ci.yml#L44-L59

https://github.com/taiki-e/install-action/blob/93a5b91855ce53b049b56dc66eecf1cf411e6057/.github/workflows/ci.yml#L105-L125

The tricky part of generating this automatically is how to handle the differences in tools supported by each platform. Another problem is that some lists contain versions or intentional spaces (for testing https://github.com/taiki-e/install-action/issues/115). For the latter, it may be reasonable to ignore these lists for now and only auto-generate the other parts.

**Comment by FirelightFlagboy** [comment]
If you reuse the manifest, you already have the list of software that is supported by each platform.

For the specific test for the spacing, it's here to test if the installation script correctly trim the space before and after. 
So it could be ignored or hard coded in the script to still have it tested.
