### ISSUE TITLE
Support for sccache

### ISSUE THREAD

**Issue by thomcc** [taiki-e/install-action#157]
It would be nice if https://github.com/mozilla/sccache could be installed this way. I have not looked into the difficulty here.

**Comment by taiki-e** [comment]
I would accept a PR to support this.

**Comment by NobodyXu** [comment]
> It would be nice if https://github.com/mozilla/sccache could be installed this way. I have not looked into the difficulty here.

Currently `install-action` would fallback to using `cargo-binstall` to install `sccache`.

**Comment by taiki-e** [comment]
Added in 2.28.0.
