### ISSUE TITLE
Add support for Ragel

### ISSUE THREAD

**Issue by notgull** [taiki-e/install-action#199]
Ragel is a code generator that would be nice for automatically generating state machines. See RazrFalcon/rustybuzz#77 for context.

Unfortunately Ragel doesn't provide a binary release; it only has a source release by default. [I'm trying to fix this](https://github.com/adrian-thurston/colm/pull/156), but until the author gets back to me I don't think there is a good way to integrate it into here.

**Comment by notgull** [comment]
cc https://github.com/adrian-thurston/ragel/issues/100

**Comment by Cloudef** [comment]
Why not use nix? https://github.com/cachix/install-nix-action
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/parsing/ragel/default.nix

**Comment by taiki-e** [comment]
it seems that https://github.com/adrian-thurston/colm/pull/156 has been closed. So, I will close this for now, but feel free to reopen the issue or open a PR if the upstream situation has improved.
