### ISSUE TITLE
Support for Biome

### ISSUE THREAD

**Issue by arendjr** [taiki-e/install-action#244]
[Biome](https://biomejs.dev) is a linter/formatter for the web that is also written in Rust. It also has releases available on GitHub: https://github.com/biomejs/biome/releases

I think it would be nice if Biome could be installed through `install-action`, especially since it's a convenient tool to invoke from a `justfile` for which you also provide support.

cc @ematipico

**Comment by taiki-e** [comment]
I would accept a PR to support this.

See [DEVELOPMENT.md](https://github.com/taiki-e/install-action/blob/main/DEVELOPMENT.md) for how to add support for a new tool.
