### ISSUE TITLE
Add `cargo-audit`

### ISSUE THREAD

**Issue by tgross35** [taiki-e/install-action#291]
`cargo-audit` has an action but unfortunately it is quite limited. It would be nice to install directly.

I see your response [here](https://github.com/taiki-e/install-action/issues/257#issuecomment-1772683847) and assume this would be the same, I'll submit a PR at some point if nobody beats me to it.

**Comment by taiki-e** [comment]
> I see your response [here](https://github.com/taiki-e/install-action/issues/257#issuecomment-1772683847) and assume this would be the same

Yeah, I would accept a PR to support this.

FWIW, this action probably already supports cargo-audit via binstall fallback, and also supports cargo-deny that provides equivalent functionality (as officially supported tool).

**Comment by tgross35** [comment]
I do use the binstall fallback :)

To my understanding cargo-deny does not support all the features of cargo-audit (I do use both). There was an open PR at some time to merge the two but then cargo-audit gained some graph traversal functionality (not sure exactly what) and the PR was closed.
