### ISSUE TITLE
Install fails on macos pipeline

### ISSUE THREAD

**Issue by Nukesor** [taiki-e/install-action#43]
Hi :)

First of all, thanks for your work on this project.
V2 seems to have introduced a bug in the macos environment.

```
Run taiki-e/install-action@v2
/Users/runner/work/_actions/taiki-e/install-action/v2/main.sh: line 533: tools[@]: unbound variable
Error: Command failed: bash --noprofile --norc /Users/runner/work/_actions/taiki-e/install-action/v2/main.sh
```

The dependabot PR can be found over here: https://github.com/Nukesor/pueue/pull/404

The action portion of `install-action` looks like this:

```yaml
      - name: cargo test
        uses: actions-rs/cargo@v1
        if: ${{ !matrix.cross }}
        env:
          NEXTEST_PROFILE: ci # defined in .config/nextest.toml
        with:
          command: nextest
          args: run --workspace --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}
```

**Comment by taiki-e** [comment]
This is a bug of the dependabot that handles non-version tags in the wrong way. 

https://github.com/Nukesor/pueue/pull/404/files?diff=unified&w=0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L78

<img width="521" alt="ss" src="https://user-images.githubusercontent.com/43724913/210802852-8a29c02f-0026-415c-9c0e-5c76e310be82.png">

They should not replace non-version tags.

**Comment by mjpieters** [comment]
Right, I've recommended that we switch from `@nextest` to `with:`, `tool: nextest` here.

Is there anything this project can do to make this error a little easier to understand? Perhaps make `tool:` a required field or give it a default, or have the script output a more helpful error message to state that nothing is being installed due to missing configuration?

**Comment by mjpieters** [comment]
The specific error (`tools[@]: unbound variable`) is only seen on macos because macos bash is stuck at version 3.x.

The `if [[ ${#tools[@]} -eq 0 ]];` test added just now is an excellent work-around for this. :-)

**Comment by taiki-e** [comment]
Changed to handle this case as a warning on all platforms. (https://github.com/taiki-e/install-action/commit/ad09286c82a7d45ee0b7f4f6e866e538587d8aef)

And thanks @mjpieters for the suggestions on improving the warning. I applied your suggestion.

**Comment by taiki-e** [comment]
FYI, I have confirmed that the Dependabot bug here has been fixed. (probably by https://github.com/dependabot/dependabot-core/pull/6743)

https://github.com/taiki-e/test/commit/ed82c3dc23edf2836910f9752007489c7b8aca54
https://github.com/taiki-e/test/pull/313/files
