### ISSUE TITLE
Use `cargo-binstall` batching mode?

### ISSUE THREAD

**Issue by NobodyXu** [taiki-e/install-action#44]
`cargo-binstall` can install multiple crates in one invocation:

```
cargo binstall cargo-nextest cargo-binstall cargo-release
```

which would download, extract and install the crates in parallel.

I'm not sure how beneficial that would be, but surely it would speed up CI if it installs multiple tools or one of the tools needs to download from a relatively slow server.

**Comment by taiki-e** [comment]
How does this interact with the `--version` option?

**Comment by NobodyXu** [comment]
> How does this interact with the `--version` option?

To specify version in batch installation:

    cargo binstall cargo-nextest@0.23.1 cargo-binstall@0.12.0

Using --version in batch installation mode with cause a hard error.

**Comment by taiki-e** [comment]
Okay, if it can keep the same functionality as we currently have, using batch installation would be fine.
