### ISSUE TITLE
Update table in readme to mention editorconfig-checker

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/install-action#440]
I noticed that #430 did not update the table in readme.

cc @jayvdb

**Comment by jayvdb** [comment]
Sorry I forgot that.

I was thinking, it wouldnt be hard to regenerate that table from the Rust, if there were a few more fields added to the base manifest files.  I'd be happy to do that over the weekend if you were interested in that.

**Comment by taiki-e** [comment]
> I was thinking, it wouldnt be hard to regenerate that table from the Rust, if there were a few more fields added to the base manifest files.

This sounds like a great idea!
