### ISSUE TITLE
Creating a manifest for nextest

### ISSUE THREAD

**Issue by jayvdb** [taiki-e/install-action#487]
nextest is currently a special case found at https://github.com/taiki-e/install-action/pull/473#discussion_r1606066064

It seems reasonable for this popular tool to be supported directly by this action, so binstall doesnt need to be used for it.

Is there anything that needs to be done in order to avoid breaking existing users who are using the "nextest" tool - i.e. switching them from binstall to native manifest installs?

**Comment by taiki-e** [comment]
See https://github.com/taiki-e/install-action/pull/183 for the context.

It is my experience that installation via binstall is considerably less reliable than the natively supported tools in install-action, especially when GITHUB_TOKEN is not set up, but the netest maintainers said they preferred it, so I will leave it to them to decide.

**Comment by jayvdb** [comment]
Interesting!  I have been thinking about https://github.com/taiki-e/install-action/issues/488 for a while now, and had starting writing it up.

IMO we should address the yanking problem, but the needs of the user are more important.

**Comment by taiki-e** [comment]
> IMO we should address the yanking problem

yanking is already respected (https://github.com/taiki-e/install-action/pull/180), However, it will not be reflected immediately, but will be reflected with a slight delay, just like a normal update. We could make it reflect immediately (see https://github.com/taiki-e/install-action/pull/182), but that would also be a way to burden crates-io's servers.

**Comment by jayvdb** [comment]
Those would still be a special case only for nextest.  IMO the solution at https://github.com/taiki-e/install-action/pull/182 , an install time / runtime check of yanked crates, should suffice, and that fixes the yanking problem for all crates, not just nextest.

**Comment by sunshowers** [comment]
Sure! Just wanted to provide an alternative in case #182 is unfeasible.

**Comment by taiki-e** [comment]
Filed #518 to revert #183 and reinstate #182.

> * The URLs as defined in https://nexte.st/book/release-urls (I believe we used to use these originally) 

This was incompatible with the checksum, so we were switched to the GH release.
