### ISSUE TITLE
codegen: Remove yanked crate

### ISSUE THREAD

**Issue by NobodyXu** [taiki-e/install-action#549]
In the cronjob, we could check for yanked crates and remove them from this action.

**Comment by taiki-e** [comment]
While yanked versions should not be selected in the latest and omitted versions (this is already implemented), I don't think they should be disallowed from being used when explicitly specified. As far as I know, cargo is also moving in that direction: https://github.com/rust-lang/cargo/pull/13974

**Comment by taiki-e** [comment]
> default to skip the yanked version

Unless you explicitly specify the full version (`tool: <tool>@<major>.<minor>.<patch>`), this is already the default.

**Comment by taiki-e** [comment]
I think it is good to warn if the yanked version is explicitly selected, but I don't think we should change the version on our own.

**Comment by NobodyXu** [comment]
Thank you!
