### ISSUE TITLE
pass GITHUB_TOKEN for cargo binstall for per-ip rate limit

### ISSUE THREAD

**Issue by anatawa12** [taiki-e/install-action#561]
In some case, cargo binstall will face API per-ip rate limit on github actions runner (due to shared ip address).

As a solution, I want install-action to have an feature to pass github.token to cargo binstall as a GITHUB_TOKEN environment variable or parameter.

https://github.com/vrc-get/vrc-get/actions/runs/9664217883/job/26658335596#step:7:1

As a workaround, we can specify `env: { GITHUB_TOKEN: ${{ github.token }} }`

**Comment by taiki-e** [comment]
See https://github.com/taiki-e/install-action/issues/556 for the previous discussion.

**Comment by simonsan** [comment]
Same problems here, whenever I work on editing/improving a workflow and need to run it more often, like every 3-5 Minutes, and make a lot of requests - this would be indeed helpful.

**Comment by NobodyXu** [comment]
cc @taiki-e maybe we should reopen the PR to pass `secrets.GITHUB_TOKEN`?

**Comment by taiki-e** [comment]
#556 has been released in 2.46.0.
