### ISSUE TITLE
Suggestion/Supporting cargo-binstall?

### ISSUE THREAD

**Issue by NobodyXu** [taiki-e/install-action#7]
[`cargo-binstall`](https://github.com/ryankurte/cargo-binstall) seems like an awesome tool for CI to avoid building binaries.

It support manifest discovery via:
 - Fetch crate / manifest via [crates.io](crates.io)
 - Fetch build from the [quickinstall](https://github.com/alsuren/cargo-quickinstall) repository, which contains a lot of pre-compiled binary packages

**Comment by taiki-e** [comment]
I would accept a PR to support cargo-binstall.
