### ISSUE TITLE
add to supported tools: `cargo-auditable`

### ISSUE THREAD

**Issue by simonsan** [taiki-e/install-action#740]
I think it would be nice, to have that as a supported tool. binstall fallback is working, but it's still taking a while.

https://github.com/rust-secure-code/cargo-auditable

**Comment by taiki-e** [comment]
I would accept a PR to support this.

See [DEVELOPMENT.md](https://github.com/taiki-e/install-action/blob/main/DEVELOPMENT.md) for how to add support for a new tool.
